import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { getIsLogin, getRole, getName } from '@/lib/getProfile';

const poppins = Poppins({ weight: [ '200', '400', '600', '800'], subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const role = getRole();
  const name = getName();
  const isLogin = getIsLogin();
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar role={role} name={name} isLogin={isLogin}/>
        {children}
        <Footer />
        </body>
    </html>
  )
}